epochs: 100
learning_rate: 0.001
batch_size: 16

optimizer:
  type: "Adam"
  weight_decay: 0.0005
  betas: [0.9, 0.999]

scheduler:
  type: "StepLR"
  step_size: 30
  gamma: 0.1

loss:
  box_loss_gain: 7.5
  cls_loss_gain: 0.5
  dfl_loss_gain: 1.5

early_stopping:
  enabled: true
  patience: 10
  min_delta: 0.001
  monitor: "val_loss"

checkpoint:
  save_best: true
  save_last: true
  save_every: 10

validation:
  interval: 1
  save_predictions: true